version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  publish:
    executor: maven/maven
    steps:
      - checkout
      - run:
          name: Publish
          command: mvn -B deploy --settings settings.xml

workflows:
  test:
    jobs:
      - maven/test:
          name: test
          filters:
            tags:
              ignore: /\d+\.\d+\.\d+/
  deploy:
    jobs:
      - publish:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/